services:
  redis:
    image: redis:7.0.0-alpine
    command: redis-server --dir /data/redis --maxclients 992 --port 6379 --save 60 1
    ports:
      - 6379:6379
    volumes:
      - ./snapshot-1/redis:/data/redis
  noms:
    image: ndau/noms:latest
    command: serve --port 8000 /data/noms
    ports:
      - 8000:8000
    volumes:
      - ./snapshot-1/noms:/data/noms
    healthcheck:
      test: netstat -an | grep 8000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 2s
      retries: 3
    depends_on:
      - redis
  ndaunode:
    image: ndau/commands:2.0.2-alpha
    pull_policy: always
    command: /bin/ndaunode -spec http://172.17.0.1:8000 -index 172.17.0.1:6379 -addr 0.0.0.0:26650
    environment:
      NDAUHOME: /data/ndau
    ports:
      - 26650:26650
    volumes:
      - ./snapshot-1/ndau:/data/ndau
    healthcheck:
      test: netstat -an | grep 26650 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 2s
      retries: 3
    depends_on:
      noms:
          condition: service_healthy
  tendermint:
    image: ndau/tendermint:0.33.1.5.005
    pull_policy: always
    #image: tendermint/tendermint:v0.33.0
    command:
      - node
      - --home=/data/tendermint
      - --proxy_app=tcp://172.17.0.1:26650
      - --p2p.laddr=tcp://0.0.0.0:26660
      - --rpc.laddr=tcp://0.0.0.0:26670
      - --consensus.create_empty_blocks=false
      - --consensus.create_empty_blocks_interval=10s
      - --p2p.persistent_peers=49b08ed396e190717e6c2c64620cb4529f3519a7@testnet-0.ndau.tech:26660,d6333397905f8d35504007f0aaf235039a2fbc2d@testnet-2.ndau.tech:26660,10127e995c8dba09fe8352d345f9add0d7e8297a@testnet-3.ndau.tech:26660
      - --log_level=info
    ports:
      - 26660:26660
      - 26670:26670
    #environment:
    #  PERSISTENT_PEERS: 49b08ed396e190717e6c2c64620cb4529f3519a7@mainnet-0.ndau.tech:26661,3823adecffd2d8bd7cd4ff9752ff70de5b889af8@mainnet-1.ndau.tech:26661,d6333397905f8d35504007f0aaf235039a2fbc2d@mainnet-2.ndau.tech:26661,10127e995c8dba09fe8352d345f9add0d7e8297a@mainnet-3.ndau.tech:26661,9ccc286a6099b2187b349d38db55f9d81ac6c5ea@mainnet-4.ndau.tech:26661
    # - --p2p.persistent_peers=49b08ed396e190717e6c2c64620cb4529f3519a7@testnet-0.ndau.tech:26660,3823adecffd2d8bd7cd4ff9752ff70de5b889af8@testnet-1.ndau.tech:26660,d6333397905f8d35504007f0aaf235039a2fbc2d@testnet-2.ndau.tech:26660,10127e995c8dba09fe8352d345f9add0d7e8297a@testnet-3.ndau.tech:26660
    # - --p2p.persistent_peers=49b08ed396e190717e6c2c64620cb4529f3519a7@testnet-0.ndau.tech:26660,3823adecffd2d8bd7cd4ff9752ff70de5b889af8@testnet-1.ndau.tech:26660,d6333397905f8d35504007f0aaf235039a2fbc2d@testnet-2.ndau.tech:26660,10127e995c8dba09fe8352d345f9add0d7e8297a@testnet-3.ndau.tech:26660
    # - --p2p.persistent_peers=3823adecffd2d8bd7cd4ff9752ff70de5b889af8@testnet-1.ndau.tech:26660
    # - --p2p.persistent_peers=49b08ed396e190717e6c2c64620cb4529f3519a7@testnet-0.ndau.tech:26660,d6333397905f8d35504007f0aaf235039a2fbc2d@testnet-2.ndau.tech:26660,10127e995c8dba09fe8352d345f9add0d7e8297a@testnet-3.ndau.tech:26660
      
    volumes:
      - ./snapshot-1/tendermint:/data/tendermint
    healthcheck:
      test: netstat -an | grep 26670 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 5s
      retries: 3
    depends_on:
      ndaunode:
          condition: service_healthy
  ndauapi:
    image: ndau/commands:latest
    command: /bin/ndauapi
    environment:
      NDAUAPI_NDAU_RPC_URL: http://172.17.0.1:26670
    ports:
      - 3030:3030
    volumes:
      - ./snapshot-1/ndau:/data/ndau
    depends_on:
      tendermint:
          condition: service_healthy
  
  
  
  
