// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/oneiro-ndev/chaincode/pkg/chain"
	"github.com/oneiro-ndev/chaincode/pkg/vm"
	"github.com/oneiro-ndev/ndaumath/pkg/constants"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Result",
			pos:  position{line: 13, col: 1, offset: 212},
			expr: &choiceExpr{
				pos: position{line: 14, col: 7, offset: 228},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 14, col: 7, offset: 228},
						run: (*parser).callonResult2,
						expr: &seqExpr{
							pos: position{line: 14, col: 7, offset: 228},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 14, col: 7, offset: 228},
									label: "v",
									expr: &ruleRefExpr{
										pos:  position{line: 14, col: 9, offset: 230},
										name: "Values",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 14, col: 16, offset: 237},
									name: "EOF",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 15, col: 7, offset: 303},
						run: (*parser).callonResult7,
						expr: &ruleRefExpr{
							pos:  position{line: 15, col: 7, offset: 303},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Values",
			pos:  position{line: 18, col: 1, offset: 377},
			expr: &choiceExpr{
				pos: position{line: 19, col: 7, offset: 393},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 19, col: 7, offset: 393},
						run: (*parser).callonValues2,
						expr: &labeledExpr{
							pos:   position{line: 19, col: 7, offset: 393},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 19, col: 9, offset: 395},
								name: "Value",
							},
						},
					},
					&actionExpr{
						pos: position{line: 20, col: 7, offset: 478},
						run: (*parser).callonValues5,
						expr: &seqExpr{
							pos: position{line: 20, col: 7, offset: 478},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 20, col: 7, offset: 478},
									label: "vs",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 10, offset: 481},
										name: "Values",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 20, col: 17, offset: 488},
									expr: &litMatcher{
										pos:        position{line: 20, col: 17, offset: 488},
										val:        ",",
										ignoreCase: false,
									},
								},
								&labeledExpr{
									pos:   position{line: 20, col: 22, offset: 493},
									label: "v",
									expr: &ruleRefExpr{
										pos:  position{line: 20, col: 24, offset: 495},
										name: "Value",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 26, col: 1, offset: 603},
			expr: &choiceExpr{
				pos: position{line: 27, col: 7, offset: 618},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 27, col: 7, offset: 618},
						name: "Timestamp",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 7, offset: 634},
						name: "Account",
					},
					&ruleRefExpr{
						pos:  position{line: 29, col: 7, offset: 648},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 30, col: 7, offset: 661},
						name: "Napu",
					},
					&ruleRefExpr{
						pos:  position{line: 31, col: 7, offset: 672},
						name: "Ndau",
					},
					&ruleRefExpr{
						pos:  position{line: 32, col: 7, offset: 683},
						name: "QuotedString",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 7, offset: 702},
						name: "HexBytes",
					},
					&ruleRefExpr{
						pos:  position{line: 34, col: 7, offset: 717},
						name: "List",
					},
					&ruleRefExpr{
						pos:  position{line: 35, col: 7, offset: 728},
						name: "Struct",
					},
				},
			},
		},
		{
			name: "Timestamp",
			pos:  position{line: 38, col: 1, offset: 742},
			expr: &actionExpr{
				pos: position{line: 38, col: 14, offset: 755},
				run: (*parser).callonTimestamp1,
				expr: &seqExpr{
					pos: position{line: 38, col: 14, offset: 755},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 38, col: 14, offset: 755},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 38, col: 16, offset: 757},
							label: "ts",
							expr: &seqExpr{
								pos: position{line: 38, col: 20, offset: 761},
								exprs: []interface{}{
									&oneOrMoreExpr{
										pos: position{line: 38, col: 20, offset: 761},
										expr: &charClassMatcher{
											pos:        position{line: 38, col: 20, offset: 761},
											val:        "[0-9-]",
											chars:      []rune{'-'},
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&litMatcher{
										pos:        position{line: 38, col: 28, offset: 769},
										val:        "T",
										ignoreCase: false,
									},
									&oneOrMoreExpr{
										pos: position{line: 38, col: 32, offset: 773},
										expr: &charClassMatcher{
											pos:        position{line: 38, col: 32, offset: 773},
											val:        "[0-9:]",
											chars:      []rune{':'},
											ranges:     []rune{'0', '9'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&litMatcher{
										pos:        position{line: 38, col: 40, offset: 781},
										val:        "Z",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Account",
			pos:  position{line: 40, col: 1, offset: 829},
			expr: &actionExpr{
				pos: position{line: 40, col: 12, offset: 840},
				run: (*parser).callonAccount1,
				expr: &seqExpr{
					pos: position{line: 40, col: 12, offset: 840},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 40, col: 12, offset: 840},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 40, col: 14, offset: 842},
							val:        "account",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 42, col: 1, offset: 919},
			expr: &choiceExpr{
				pos: position{line: 43, col: 7, offset: 935},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 43, col: 7, offset: 935},
						name: "BinaryNumber",
					},
					&ruleRefExpr{
						pos:  position{line: 44, col: 7, offset: 954},
						name: "OctalNumber",
					},
					&ruleRefExpr{
						pos:  position{line: 45, col: 7, offset: 972},
						name: "HexNumber",
					},
					&ruleRefExpr{
						pos:  position{line: 46, col: 7, offset: 988},
						name: "DecimalNumber",
					},
				},
			},
		},
		{
			name: "BinaryNumber",
			pos:  position{line: 49, col: 1, offset: 1009},
			expr: &actionExpr{
				pos: position{line: 49, col: 17, offset: 1025},
				run: (*parser).callonBinaryNumber1,
				expr: &seqExpr{
					pos: position{line: 49, col: 17, offset: 1025},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 49, col: 17, offset: 1025},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 49, col: 19, offset: 1027},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 49, col: 21, offset: 1029},
								name: "BinaryValue",
							},
						},
					},
				},
			},
		},
		{
			name: "BinaryValue",
			pos:  position{line: 54, col: 1, offset: 1129},
			expr: &actionExpr{
				pos: position{line: 54, col: 16, offset: 1144},
				run: (*parser).callonBinaryValue1,
				expr: &seqExpr{
					pos: position{line: 54, col: 16, offset: 1144},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 54, col: 16, offset: 1144},
							val:        "0b",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 54, col: 21, offset: 1149},
							expr: &charClassMatcher{
								pos:        position{line: 54, col: 21, offset: 1149},
								val:        "[01_]",
								chars:      []rune{'0', '1', '_'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "OctalNumber",
			pos:  position{line: 56, col: 1, offset: 1205},
			expr: &actionExpr{
				pos: position{line: 56, col: 16, offset: 1220},
				run: (*parser).callonOctalNumber1,
				expr: &seqExpr{
					pos: position{line: 56, col: 16, offset: 1220},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 56, col: 16, offset: 1220},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 56, col: 18, offset: 1222},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 20, offset: 1224},
								name: "OctalValue",
							},
						},
					},
				},
			},
		},
		{
			name: "OctalValue",
			pos:  position{line: 61, col: 1, offset: 1323},
			expr: &actionExpr{
				pos: position{line: 61, col: 15, offset: 1337},
				run: (*parser).callonOctalValue1,
				expr: &seqExpr{
					pos: position{line: 61, col: 15, offset: 1337},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 61, col: 15, offset: 1337},
							val:        "0",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 61, col: 19, offset: 1341},
							expr: &charClassMatcher{
								pos:        position{line: 61, col: 19, offset: 1341},
								val:        "[0-7_]",
								chars:      []rune{'_'},
								ranges:     []rune{'0', '7'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "HexNumber",
			pos:  position{line: 63, col: 1, offset: 1399},
			expr: &actionExpr{
				pos: position{line: 63, col: 14, offset: 1412},
				run: (*parser).callonHexNumber1,
				expr: &seqExpr{
					pos: position{line: 63, col: 14, offset: 1412},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 63, col: 14, offset: 1412},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 16, offset: 1414},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 18, offset: 1416},
								name: "HexValue",
							},
						},
					},
				},
			},
		},
		{
			name: "HexValue",
			pos:  position{line: 68, col: 1, offset: 1513},
			expr: &actionExpr{
				pos: position{line: 68, col: 13, offset: 1525},
				run: (*parser).callonHexValue1,
				expr: &seqExpr{
					pos: position{line: 68, col: 13, offset: 1525},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 68, col: 13, offset: 1525},
							val:        "0x",
							ignoreCase: false,
						},
						&oneOrMoreExpr{
							pos: position{line: 68, col: 18, offset: 1530},
							expr: &charClassMatcher{
								pos:        position{line: 68, col: 18, offset: 1530},
								val:        "[0-9a-fA-F_]",
								chars:      []rune{'_'},
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalNumber",
			pos:  position{line: 70, col: 1, offset: 1589},
			expr: &actionExpr{
				pos: position{line: 70, col: 18, offset: 1606},
				run: (*parser).callonDecimalNumber1,
				expr: &seqExpr{
					pos: position{line: 70, col: 18, offset: 1606},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 70, col: 18, offset: 1606},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 20, offset: 1608},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 22, offset: 1610},
								name: "DecimalValue",
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalValue",
			pos:  position{line: 75, col: 1, offset: 1711},
			expr: &actionExpr{
				pos: position{line: 75, col: 17, offset: 1727},
				run: (*parser).callonDecimalValue1,
				expr: &seqExpr{
					pos: position{line: 75, col: 17, offset: 1727},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 75, col: 17, offset: 1727},
							expr: &litMatcher{
								pos:        position{line: 75, col: 17, offset: 1727},
								val:        "-",
								ignoreCase: false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 75, col: 22, offset: 1732},
							expr: &charClassMatcher{
								pos:        position{line: 75, col: 22, offset: 1732},
								val:        "[0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Napu",
			pos:  position{line: 77, col: 1, offset: 1787},
			expr: &actionExpr{
				pos: position{line: 77, col: 9, offset: 1795},
				run: (*parser).callonNapu1,
				expr: &seqExpr{
					pos: position{line: 77, col: 9, offset: 1795},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 77, col: 9, offset: 1795},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 77, col: 11, offset: 1797},
							val:        "np",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 77, col: 16, offset: 1802},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 77, col: 18, offset: 1804},
								name: "DecimalValue",
							},
						},
					},
				},
			},
		},
		{
			name: "Ndau",
			pos:  position{line: 83, col: 1, offset: 2014},
			expr: &actionExpr{
				pos: position{line: 83, col: 9, offset: 2022},
				run: (*parser).callonNdau1,
				expr: &seqExpr{
					pos: position{line: 83, col: 9, offset: 2022},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 83, col: 9, offset: 2022},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 83, col: 11, offset: 2024},
							val:        "nd",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 83, col: 16, offset: 2029},
							label: "n",
							expr: &ruleRefExpr{
								pos:  position{line: 83, col: 18, offset: 2031},
								name: "FloatValue",
							},
						},
					},
				},
			},
		},
		{
			name: "FloatValue",
			pos:  position{line: 89, col: 1, offset: 2281},
			expr: &choiceExpr{
				pos: position{line: 90, col: 7, offset: 2301},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 90, col: 7, offset: 2301},
						run: (*parser).callonFloatValue2,
						expr: &seqExpr{
							pos: position{line: 90, col: 7, offset: 2301},
							exprs: []interface{}{
								&zeroOrMoreExpr{
									pos: position{line: 90, col: 7, offset: 2301},
									expr: &charClassMatcher{
										pos:        position{line: 90, col: 7, offset: 2301},
										val:        "[0-9_]",
										chars:      []rune{'_'},
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 90, col: 15, offset: 2309},
									val:        ".",
									ignoreCase: false,
								},
								&oneOrMoreExpr{
									pos: position{line: 90, col: 19, offset: 2313},
									expr: &charClassMatcher{
										pos:        position{line: 90, col: 19, offset: 2313},
										val:        "[0-9_]",
										chars:      []rune{'_'},
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 91, col: 7, offset: 2376},
						run: (*parser).callonFloatValue9,
						expr: &seqExpr{
							pos: position{line: 91, col: 7, offset: 2376},
							exprs: []interface{}{
								&oneOrMoreExpr{
									pos: position{line: 91, col: 7, offset: 2376},
									expr: &charClassMatcher{
										pos:        position{line: 91, col: 7, offset: 2376},
										val:        "[0-9_]",
										chars:      []rune{'_'},
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&litMatcher{
									pos:        position{line: 91, col: 15, offset: 2384},
									val:        ".",
									ignoreCase: false,
								},
								&oneOrMoreExpr{
									pos: position{line: 91, col: 19, offset: 2388},
									expr: &charClassMatcher{
										pos:        position{line: 91, col: 19, offset: 2388},
										val:        "[0-9_]",
										chars:      []rune{'_'},
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 92, col: 7, offset: 2451},
						run: (*parser).callonFloatValue16,
						expr: &seqExpr{
							pos: position{line: 92, col: 7, offset: 2451},
							exprs: []interface{}{
								&oneOrMoreExpr{
									pos: position{line: 92, col: 7, offset: 2451},
									expr: &charClassMatcher{
										pos:        position{line: 92, col: 7, offset: 2451},
										val:        "[0-9_]",
										chars:      []rune{'_'},
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 92, col: 15, offset: 2459},
									expr: &litMatcher{
										pos:        position{line: 92, col: 15, offset: 2459},
										val:        ".",
										ignoreCase: false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "QuotedString",
			pos:  position{line: 95, col: 1, offset: 2527},
			expr: &choiceExpr{
				pos: position{line: 96, col: 7, offset: 2549},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 96, col: 7, offset: 2549},
						name: "TripleSingle",
					},
					&ruleRefExpr{
						pos:  position{line: 97, col: 7, offset: 2568},
						name: "TripleDouble",
					},
					&ruleRefExpr{
						pos:  position{line: 98, col: 7, offset: 2587},
						name: "DoubleQuote",
					},
					&ruleRefExpr{
						pos:  position{line: 99, col: 7, offset: 2605},
						name: "SingleQuote",
					},
				},
			},
		},
		{
			name: "TripleSingle",
			pos:  position{line: 102, col: 1, offset: 2624},
			expr: &actionExpr{
				pos: position{line: 102, col: 17, offset: 2640},
				run: (*parser).callonTripleSingle1,
				expr: &seqExpr{
					pos: position{line: 102, col: 17, offset: 2640},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 102, col: 17, offset: 2640},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 102, col: 19, offset: 2642},
							val:        "'''",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 102, col: 25, offset: 2648},
							label: "s",
							expr: &zeroOrMoreExpr{
								pos: position{line: 102, col: 28, offset: 2651},
								expr: &anyMatcher{
									line: 102, col: 28, offset: 2651,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 102, col: 32, offset: 2655},
							val:        "'''",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "TripleDouble",
			pos:  position{line: 103, col: 1, offset: 2708},
			expr: &actionExpr{
				pos: position{line: 103, col: 17, offset: 2724},
				run: (*parser).callonTripleDouble1,
				expr: &seqExpr{
					pos: position{line: 103, col: 17, offset: 2724},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 103, col: 17, offset: 2724},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 103, col: 19, offset: 2726},
							val:        "\"\"\"",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 103, col: 28, offset: 2735},
							label: "s",
							expr: &zeroOrMoreExpr{
								pos: position{line: 103, col: 31, offset: 2738},
								expr: &anyMatcher{
									line: 103, col: 31, offset: 2738,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 103, col: 35, offset: 2742},
							val:        "\"\"\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "DoubleQuote",
			pos:  position{line: 104, col: 1, offset: 2792},
			expr: &actionExpr{
				pos: position{line: 104, col: 16, offset: 2807},
				run: (*parser).callonDoubleQuote1,
				expr: &seqExpr{
					pos: position{line: 104, col: 16, offset: 2807},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 104, col: 16, offset: 2807},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 104, col: 18, offset: 2809},
							val:        "\"",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 104, col: 22, offset: 2813},
							label: "s",
							expr: &zeroOrMoreExpr{
								pos: position{line: 104, col: 25, offset: 2816},
								expr: &charClassMatcher{
									pos:        position{line: 104, col: 25, offset: 2816},
									val:        "[^\"]",
									chars:      []rune{'"'},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 104, col: 32, offset: 2823},
							val:        "\"",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "SingleQuote",
			pos:  position{line: 105, col: 1, offset: 2876},
			expr: &actionExpr{
				pos: position{line: 105, col: 16, offset: 2891},
				run: (*parser).callonSingleQuote1,
				expr: &seqExpr{
					pos: position{line: 105, col: 16, offset: 2891},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 105, col: 16, offset: 2891},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 105, col: 18, offset: 2893},
							val:        "'",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 105, col: 22, offset: 2897},
							label: "s",
							expr: &zeroOrMoreExpr{
								pos: position{line: 105, col: 25, offset: 2900},
								expr: &charClassMatcher{
									pos:        position{line: 105, col: 25, offset: 2900},
									val:        "[^']",
									chars:      []rune{'\''},
									ignoreCase: false,
									inverted:   true,
								},
							},
						},
						&litMatcher{
							pos:        position{line: 105, col: 32, offset: 2907},
							val:        "'",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "HexBytes",
			pos:  position{line: 107, col: 1, offset: 2961},
			expr: &actionExpr{
				pos: position{line: 107, col: 13, offset: 2973},
				run: (*parser).callonHexBytes1,
				expr: &seqExpr{
					pos: position{line: 107, col: 13, offset: 2973},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 107, col: 13, offset: 2973},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 107, col: 15, offset: 2975},
							val:        "B(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 107, col: 20, offset: 2980},
							label: "bs",
							expr: &oneOrMoreExpr{
								pos: position{line: 107, col: 24, offset: 2984},
								expr: &seqExpr{
									pos: position{line: 107, col: 25, offset: 2985},
									exprs: []interface{}{
										&charClassMatcher{
											pos:        position{line: 107, col: 25, offset: 2985},
											val:        "[0-9A-Fa-f]",
											ranges:     []rune{'0', '9', 'A', 'F', 'a', 'f'},
											ignoreCase: false,
											inverted:   false,
										},
										&charClassMatcher{
											pos:        position{line: 107, col: 36, offset: 2996},
											val:        "[0-9A-Fa-f]",
											ranges:     []rune{'0', '9', 'A', 'F', 'a', 'f'},
											ignoreCase: false,
											inverted:   false,
										},
										&zeroOrMoreExpr{
											pos: position{line: 107, col: 47, offset: 3007},
											expr: &charClassMatcher{
												pos:        position{line: 107, col: 47, offset: 3007},
												val:        "[_ ]",
												chars:      []rune{'_', ' '},
												ignoreCase: false,
												inverted:   false,
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 107, col: 56, offset: 3016},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Struct",
			pos:  position{line: 118, col: 1, offset: 3459},
			expr: &actionExpr{
				pos: position{line: 118, col: 11, offset: 3469},
				run: (*parser).callonStruct1,
				expr: &seqExpr{
					pos: position{line: 118, col: 11, offset: 3469},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 118, col: 11, offset: 3469},
							name: "StructStart",
						},
						&labeledExpr{
							pos:   position{line: 118, col: 23, offset: 3481},
							label: "fl",
							expr: &zeroOrOneExpr{
								pos: position{line: 118, col: 26, offset: 3484},
								expr: &ruleRefExpr{
									pos:  position{line: 118, col: 26, offset: 3484},
									name: "Fields",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 34, offset: 3492},
							name: "StructEnd",
						},
					},
				},
			},
		},
		{
			name: "Fields",
			pos:  position{line: 130, col: 1, offset: 3792},
			expr: &choiceExpr{
				pos: position{line: 131, col: 7, offset: 3808},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 131, col: 7, offset: 3808},
						run: (*parser).callonFields2,
						expr: &labeledExpr{
							pos:   position{line: 131, col: 7, offset: 3808},
							label: "f",
							expr: &ruleRefExpr{
								pos:  position{line: 131, col: 9, offset: 3810},
								name: "Field",
							},
						},
					},
					&actionExpr{
						pos: position{line: 132, col: 7, offset: 3893},
						run: (*parser).callonFields5,
						expr: &seqExpr{
							pos: position{line: 132, col: 7, offset: 3893},
							exprs: []interface{}{
								&labeledExpr{
									pos:   position{line: 132, col: 7, offset: 3893},
									label: "fs",
									expr: &ruleRefExpr{
										pos:  position{line: 132, col: 10, offset: 3896},
										name: "Fields",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 132, col: 17, offset: 3903},
									expr: &litMatcher{
										pos:        position{line: 132, col: 17, offset: 3903},
										val:        ",",
										ignoreCase: false,
									},
								},
								&labeledExpr{
									pos:   position{line: 132, col: 22, offset: 3908},
									label: "f",
									expr: &ruleRefExpr{
										pos:  position{line: 132, col: 24, offset: 3910},
										name: "Field",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Field",
			pos:  position{line: 138, col: 1, offset: 4018},
			expr: &actionExpr{
				pos: position{line: 138, col: 10, offset: 4027},
				run: (*parser).callonField1,
				expr: &seqExpr{
					pos: position{line: 138, col: 10, offset: 4027},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 138, col: 10, offset: 4027},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 138, col: 12, offset: 4029},
							label: "id",
							expr: &ruleRefExpr{
								pos:  position{line: 138, col: 15, offset: 4032},
								name: "FieldID",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 138, col: 23, offset: 4040},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 138, col: 25, offset: 4042},
							val:        ":",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 138, col: 29, offset: 4046},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 138, col: 31, offset: 4048},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "FieldID",
			pos:  position{line: 150, col: 1, offset: 4458},
			expr: &actionExpr{
				pos: position{line: 150, col: 12, offset: 4469},
				run: (*parser).callonFieldID1,
				expr: &choiceExpr{
					pos: position{line: 150, col: 14, offset: 4471},
					alternatives: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 150, col: 14, offset: 4471},
							expr: &charClassMatcher{
								pos:        position{line: 150, col: 14, offset: 4471},
								val:        "[0-9]",
								ranges:     []rune{'0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 150, col: 23, offset: 4480},
							expr: &charClassMatcher{
								pos:        position{line: 150, col: 23, offset: 4480},
								val:        "[A-Z_]",
								chars:      []rune{'_'},
								ranges:     []rune{'A', 'Z'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 152, col: 1, offset: 4534},
			expr: &actionExpr{
				pos: position{line: 152, col: 9, offset: 4542},
				run: (*parser).callonList1,
				expr: &seqExpr{
					pos: position{line: 152, col: 9, offset: 4542},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 152, col: 9, offset: 4542},
							name: "ListStart",
						},
						&labeledExpr{
							pos:   position{line: 152, col: 19, offset: 4552},
							label: "vs",
							expr: &zeroOrOneExpr{
								pos: position{line: 152, col: 22, offset: 4555},
								expr: &ruleRefExpr{
									pos:  position{line: 152, col: 22, offset: 4555},
									name: "Values",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 152, col: 30, offset: 4563},
							name: "ListEnd",
						},
					},
				},
			},
		},
		{
			name: "StructStart",
			pos:  position{line: 154, col: 1, offset: 4626},
			expr: &seqExpr{
				pos: position{line: 154, col: 16, offset: 4641},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 154, col: 16, offset: 4641},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 154, col: 18, offset: 4643},
						val:        "{",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "StructEnd",
			pos:  position{line: 155, col: 1, offset: 4647},
			expr: &seqExpr{
				pos: position{line: 155, col: 14, offset: 4660},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 155, col: 14, offset: 4660},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 155, col: 16, offset: 4662},
						val:        "}",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "ListStart",
			pos:  position{line: 156, col: 1, offset: 4666},
			expr: &seqExpr{
				pos: position{line: 156, col: 14, offset: 4679},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 156, col: 14, offset: 4679},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 156, col: 16, offset: 4681},
						val:        "[",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "ListEnd",
			pos:  position{line: 157, col: 1, offset: 4685},
			expr: &seqExpr{
				pos: position{line: 157, col: 12, offset: 4696},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 157, col: 12, offset: 4696},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 157, col: 14, offset: 4698},
						val:        "]",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 159, col: 1, offset: 4703},
			expr: &zeroOrMoreExpr{
				pos: position{line: 159, col: 6, offset: 4708},
				expr: &charClassMatcher{
					pos:        position{line: 159, col: 6, offset: 4708},
					val:        "[ \\t]",
					chars:      []rune{' ', '\t'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 161, col: 1, offset: 4716},
			expr: &seqExpr{
				pos: position{line: 161, col: 12, offset: 4727},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 161, col: 12, offset: 4727},
						val:        ";",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 161, col: 16, offset: 4731},
						expr: &charClassMatcher{
							pos:        position{line: 161, col: 16, offset: 4731},
							val:        "[^\\r\\n]",
							chars:      []rune{'\r', '\n'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 163, col: 1, offset: 4741},
			expr: &choiceExpr{
				pos: position{line: 164, col: 7, offset: 4754},
				alternatives: []interface{}{
					&notExpr{
						pos: position{line: 164, col: 7, offset: 4754},
						expr: &anyMatcher{
							line: 164, col: 8, offset: 4755,
						},
					},
					&seqExpr{
						pos: position{line: 165, col: 7, offset: 4763},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 165, col: 7, offset: 4763},
								name: "Comment",
							},
							&notExpr{
								pos: position{line: 165, col: 15, offset: 4771},
								expr: &anyMatcher{
									line: 165, col: 16, offset: 4772,
								},
							},
						},
					},
				},
			},
		},
	},
}

func (c *current) onResult2(v interface{}) (interface{}, error) {
	return v.([]vm.Value), nil
}

func (p *parser) callonResult2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onResult2(stack["v"])
}

func (c *current) onResult7() (interface{}, error) {
	return []vm.Value{}, nil
}

func (p *parser) callonResult7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onResult7()
}

func (c *current) onValues2(v interface{}) (interface{}, error) {
	return []vm.Value{v.(vm.Value)}, nil
}

func (p *parser) callonValues2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValues2(stack["v"])
}

func (c *current) onValues5(vs, v interface{}) (interface{}, error) {
	va := append(vs.([]vm.Value), v.(vm.Value))
	return va, nil

}

func (p *parser) callonValues5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValues5(stack["vs"], stack["v"])
}

func (c *current) onTimestamp1(ts interface{}) (interface{}, error) {
	return vm.ParseTimestamp(ts.(string))
}

func (p *parser) callonTimestamp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTimestamp1(stack["ts"])
}

func (c *current) onAccount1() (interface{}, error) {
	return chain.ToValue(getRandomAccount())
}

func (p *parser) callonAccount1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccount1()
}

func (c *current) onBinaryNumber1(n interface{}) (interface{}, error) {
	x, err := parseInt(n.(string), 64)
	return vm.NewNumber(x), err

}

func (p *parser) callonBinaryNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryNumber1(stack["n"])
}

func (c *current) onBinaryValue1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonBinaryValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBinaryValue1()
}

func (c *current) onOctalNumber1(n interface{}) (interface{}, error) {
	x, err := parseInt(n.(string), 64)
	return vm.NewNumber(x), err

}

func (p *parser) callonOctalNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOctalNumber1(stack["n"])
}

func (c *current) onOctalValue1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonOctalValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOctalValue1()
}

func (c *current) onHexNumber1(n interface{}) (interface{}, error) {
	x, err := parseInt(n.(string), 64)
	return vm.NewNumber(x), err

}

func (p *parser) callonHexNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHexNumber1(stack["n"])
}

func (c *current) onHexValue1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonHexValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHexValue1()
}

func (c *current) onDecimalNumber1(n interface{}) (interface{}, error) {
	x, err := parseInt(n.(string), 64)
	return vm.NewNumber(x), err

}

func (p *parser) callonDecimalNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDecimalNumber1(stack["n"])
}

func (c *current) onDecimalValue1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonDecimalValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDecimalValue1()
}

func (c *current) onNapu1(n interface{}) (interface{}, error) {
	// napu is a base-10 positive integer preceded with np; it is delivered as an integer number of napu
	x, err := parseInt(n.(string), 64)
	return vm.NewNumber(x), err

}

func (p *parser) callonNapu1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNapu1(stack["n"])
}

func (c *current) onNdau1(n interface{}) (interface{}, error) {
	// ndau values are a base-10 positive decimal, which is multiplied by 10^8 and converted to integer
	x, err := strconv.ParseFloat(n.(string), 64)
	return vm.NewNumber(int64(x * constants.QuantaPerUnit)), err

}

func (p *parser) callonNdau1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNdau1(stack["n"])
}

func (c *current) onFloatValue2() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonFloatValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloatValue2()
}

func (c *current) onFloatValue9() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonFloatValue9() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloatValue9()
}

func (c *current) onFloatValue16() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonFloatValue16() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFloatValue16()
}

func (c *current) onTripleSingle1(s interface{}) (interface{}, error) {
	return vm.NewBytes(s.([]byte)), nil
}

func (p *parser) callonTripleSingle1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTripleSingle1(stack["s"])
}

func (c *current) onTripleDouble1(s interface{}) (interface{}, error) {
	return vm.NewBytes(s.([]byte)), nil
}

func (p *parser) callonTripleDouble1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTripleDouble1(stack["s"])
}

func (c *current) onDoubleQuote1(s interface{}) (interface{}, error) {
	return vm.NewBytes(s.([]byte)), nil
}

func (p *parser) callonDoubleQuote1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleQuote1(stack["s"])
}

func (c *current) onSingleQuote1(s interface{}) (interface{}, error) {
	return vm.NewBytes(s.([]byte)), nil
}

func (p *parser) callonSingleQuote1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleQuote1(stack["s"])
}

func (c *current) onHexBytes1(bs interface{}) (interface{}, error) {
	// arrays of bytes are B(hex) with individual bytes as hex pairs with no 0x; embedded spaces and underscores are ignored
	ba := []byte{}
	pair := regexp.MustCompile("([0-9A-Fa-f][0-9A-Fa-f])")
	for _, it := range pair.FindAllString(bs.(string), -1) {
		b, _ := strconv.ParseInt(strings.TrimSpace(it), 16, 8)
		ba = append(ba, byte(b))
	}
	return vm.NewBytes(ba), nil

}

func (p *parser) callonHexBytes1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHexBytes1(stack["bs"])
}

func (c *current) onStruct1(fl interface{}) (interface{}, error) {
	str := vm.NewStruct()
	for _, i := range fl.([]vm.Value) {
		istr := i.(*vm.Struct)
		for _, ix := range istr.Indices() {
			v2, _ := istr.Get(ix)
			str = str.Set(ix, v2)
		}
	}
	return str, nil

}

func (p *parser) callonStruct1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStruct1(stack["fl"])
}

func (c *current) onFields2(f interface{}) (interface{}, error) {
	return []vm.Value{f.(vm.Value)}, nil
}

func (p *parser) callonFields2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFields2(stack["f"])
}

func (c *current) onFields5(fs, f interface{}) (interface{}, error) {
	fa := append(fs.([]vm.Value), f.(vm.Value))
	return fa, nil

}

func (p *parser) callonFields5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFields5(stack["fs"], stack["f"])
}

func (c *current) onField1(id, v interface{}) (interface{}, error) {
	// fields for structs are fieldid:Value; they are returned as a struct with one field that
	// is consolidated when they are enclosed in {} wrappers
	s := id.(string)
	if p, ok := predefined[s]; ok {
		s = p
	}
	fieldid, err := strconv.ParseInt(s, 10, 8)
	str := vm.NewStruct().Set(byte(fieldid), v.(vm.Value))
	return str, err

}

func (p *parser) callonField1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onField1(stack["id"], stack["v"])
}

func (c *current) onFieldID1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonFieldID1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFieldID1()
}

func (c *current) onList1(vs interface{}) (interface{}, error) {
	return vm.NewList(vs.([]vm.Value)...), nil
}

func (p *parser) callonList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["vs"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
