NodeRewardWebhookDelay = 10.0

[Features]
  # Feature heights for testnet.  See docker-config-default.toml for more information.
  NoExchangeHoldsOnTransfer = 13_510
  NoKeysOnSetValidation = 13_510
  ResetUncreditedEAIOnCreditEAI = 13_510
  NodeActiveCheck = 31_025
  NoLeakyUpdateState = 31_025
  SequenceIncrementProtection = 31_025
  CreditEAIUnlocksAccounts = 31_025
  ApplyUncreditedEAI = 31_025
  FixEAIUnlockBug = 31_025
  TargetPrice9999 = 31_025
  SysvarValidityCheck = 31_025
  NodeRegistrationDate = 50_100
  # new features: change to a sane number before upgrading mainnet
  UpdateWAAUpdateDateInDetails = 1_000_000
  AllRFEInCirculation = 203865
  NewSIBRules = 205655
