// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Grammar",
			pos:  position{line: 5, col: 1, offset: 18},
			expr: &actionExpr{
				pos: position{line: 5, col: 11, offset: 30},
				run: (*parser).callonGrammar1,
				expr: &seqExpr{
					pos: position{line: 5, col: 11, offset: 30},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 5, col: 11, offset: 30},
							name: "__",
						},
						&labeledExpr{
							pos:   position{line: 5, col: 14, offset: 33},
							label: "initializer",
							expr: &zeroOrOneExpr{
								pos: position{line: 5, col: 26, offset: 45},
								expr: &seqExpr{
									pos: position{line: 5, col: 28, offset: 47},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 5, col: 28, offset: 47},
											name: "Initializer",
										},
										&ruleRefExpr{
											pos:  position{line: 5, col: 40, offset: 59},
											name: "__",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 5, col: 46, offset: 65},
							label: "rules",
							expr: &oneOrMoreExpr{
								pos: position{line: 5, col: 52, offset: 71},
								expr: &seqExpr{
									pos: position{line: 5, col: 54, offset: 73},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 5, col: 54, offset: 73},
											name: "Rule",
										},
										&ruleRefExpr{
											pos:  position{line: 5, col: 59, offset: 78},
											name: "__",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 5, col: 65, offset: 84},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Initializer",
			pos:  position{line: 7, col: 1, offset: 141},
			expr: &seqExpr{
				pos: position{line: 7, col: 15, offset: 157},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 7, col: 15, offset: 157},
						label: "code",
						expr: &ruleRefExpr{
							pos:  position{line: 7, col: 20, offset: 162},
							name: "CodeBlock",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 7, col: 30, offset: 172},
						name: "EOS",
					},
				},
			},
		},
		{
			name: "Rule",
			pos:  position{line: 9, col: 1, offset: 177},
			expr: &seqExpr{
				pos: position{line: 9, col: 8, offset: 186},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 9, col: 8, offset: 186},
						label: "name",
						expr: &ruleRefExpr{
							pos:  position{line: 9, col: 13, offset: 191},
							name: "IdentifierName",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 28, offset: 206},
						name: "__",
					},
					&labeledExpr{
						pos:   position{line: 9, col: 31, offset: 209},
						label: "display",
						expr: &zeroOrOneExpr{
							pos: position{line: 9, col: 39, offset: 217},
							expr: &seqExpr{
								pos: position{line: 9, col: 41, offset: 219},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 9, col: 41, offset: 219},
										name: "StringLiteral",
									},
									&ruleRefExpr{
										pos:  position{line: 9, col: 55, offset: 233},
										name: "__",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 61, offset: 239},
						name: "RuleDefOp",
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 71, offset: 249},
						name: "__",
					},
					&labeledExpr{
						pos:   position{line: 9, col: 74, offset: 252},
						label: "expr",
						expr: &ruleRefExpr{
							pos:  position{line: 9, col: 79, offset: 257},
							name: "Expression",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 9, col: 90, offset: 268},
						name: "EOS",
					},
				},
			},
		},
		{
			name: "Expression",
			pos:  position{line: 11, col: 1, offset: 273},
			expr: &ruleRefExpr{
				pos:  position{line: 11, col: 14, offset: 288},
				name: "RecoveryExpr",
			},
		},
		{
			name: "RecoveryExpr",
			pos:  position{line: 13, col: 1, offset: 302},
			expr: &seqExpr{
				pos: position{line: 13, col: 16, offset: 319},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 13, col: 16, offset: 319},
						label: "expr",
						expr: &ruleRefExpr{
							pos:  position{line: 13, col: 21, offset: 324},
							name: "ChoiceExpr",
						},
					},
					&labeledExpr{
						pos:   position{line: 13, col: 32, offset: 335},
						label: "recoverExprs",
						expr: &zeroOrMoreExpr{
							pos: position{line: 13, col: 45, offset: 348},
							expr: &seqExpr{
								pos: position{line: 13, col: 47, offset: 350},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 13, col: 47, offset: 350},
										name: "__",
									},
									&litMatcher{
										pos:        position{line: 13, col: 50, offset: 353},
										val:        "//{",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 13, col: 56, offset: 359},
										name: "__",
									},
									&ruleRefExpr{
										pos:  position{line: 13, col: 59, offset: 362},
										name: "Labels",
									},
									&ruleRefExpr{
										pos:  position{line: 13, col: 66, offset: 369},
										name: "__",
									},
									&litMatcher{
										pos:        position{line: 13, col: 69, offset: 372},
										val:        "}",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 13, col: 73, offset: 376},
										name: "__",
									},
									&ruleRefExpr{
										pos:  position{line: 13, col: 76, offset: 379},
										name: "ChoiceExpr",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Labels",
			pos:  position{line: 15, col: 1, offset: 394},
			expr: &seqExpr{
				pos: position{line: 15, col: 10, offset: 405},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 15, col: 10, offset: 405},
						label: "label",
						expr: &ruleRefExpr{
							pos:  position{line: 15, col: 16, offset: 411},
							name: "IdentifierName",
						},
					},
					&labeledExpr{
						pos:   position{line: 15, col: 31, offset: 426},
						label: "labels",
						expr: &zeroOrMoreExpr{
							pos: position{line: 15, col: 38, offset: 433},
							expr: &seqExpr{
								pos: position{line: 15, col: 40, offset: 435},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 15, col: 40, offset: 435},
										name: "__",
									},
									&litMatcher{
										pos:        position{line: 15, col: 43, offset: 438},
										val:        ",",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 47, offset: 442},
										name: "__",
									},
									&ruleRefExpr{
										pos:  position{line: 15, col: 50, offset: 445},
										name: "IdentifierName",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ChoiceExpr",
			pos:  position{line: 17, col: 1, offset: 463},
			expr: &seqExpr{
				pos: position{line: 17, col: 14, offset: 478},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 17, col: 14, offset: 478},
						label: "first",
						expr: &ruleRefExpr{
							pos:  position{line: 17, col: 20, offset: 484},
							name: "ActionExpr",
						},
					},
					&labeledExpr{
						pos:   position{line: 17, col: 31, offset: 495},
						label: "rest",
						expr: &zeroOrMoreExpr{
							pos: position{line: 17, col: 36, offset: 500},
							expr: &seqExpr{
								pos: position{line: 17, col: 38, offset: 502},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 17, col: 38, offset: 502},
										name: "__",
									},
									&litMatcher{
										pos:        position{line: 17, col: 41, offset: 505},
										val:        "/",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 17, col: 45, offset: 509},
										name: "__",
									},
									&ruleRefExpr{
										pos:  position{line: 17, col: 48, offset: 512},
										name: "ActionExpr",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ActionExpr",
			pos:  position{line: 19, col: 1, offset: 527},
			expr: &seqExpr{
				pos: position{line: 19, col: 14, offset: 542},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 19, col: 14, offset: 542},
						label: "expr",
						expr: &ruleRefExpr{
							pos:  position{line: 19, col: 19, offset: 547},
							name: "SeqExpr",
						},
					},
					&labeledExpr{
						pos:   position{line: 19, col: 27, offset: 555},
						label: "code",
						expr: &zeroOrOneExpr{
							pos: position{line: 19, col: 32, offset: 560},
							expr: &seqExpr{
								pos: position{line: 19, col: 34, offset: 562},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 19, col: 34, offset: 562},
										name: "__",
									},
									&ruleRefExpr{
										pos:  position{line: 19, col: 37, offset: 565},
										name: "CodeBlock",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SeqExpr",
			pos:  position{line: 21, col: 1, offset: 579},
			expr: &seqExpr{
				pos: position{line: 21, col: 11, offset: 591},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 21, col: 11, offset: 591},
						label: "first",
						expr: &ruleRefExpr{
							pos:  position{line: 21, col: 17, offset: 597},
							name: "LabeledExpr",
						},
					},
					&labeledExpr{
						pos:   position{line: 21, col: 29, offset: 609},
						label: "rest",
						expr: &zeroOrMoreExpr{
							pos: position{line: 21, col: 34, offset: 614},
							expr: &seqExpr{
								pos: position{line: 21, col: 36, offset: 616},
								exprs: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 21, col: 36, offset: 616},
										name: "__",
									},
									&ruleRefExpr{
										pos:  position{line: 21, col: 39, offset: 619},
										name: "LabeledExpr",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LabeledExpr",
			pos:  position{line: 23, col: 1, offset: 635},
			expr: &choiceExpr{
				pos: position{line: 23, col: 15, offset: 651},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 23, col: 15, offset: 651},
						exprs: []interface{}{
							&labeledExpr{
								pos:   position{line: 23, col: 15, offset: 651},
								label: "label",
								expr: &ruleRefExpr{
									pos:  position{line: 23, col: 21, offset: 657},
									name: "Identifier",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 23, col: 32, offset: 668},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 23, col: 35, offset: 671},
								val:        ":",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 23, col: 39, offset: 675},
								name: "__",
							},
							&labeledExpr{
								pos:   position{line: 23, col: 42, offset: 678},
								label: "expr",
								expr: &ruleRefExpr{
									pos:  position{line: 23, col: 47, offset: 683},
									name: "PrefixedExpr",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 63, offset: 699},
						name: "PrefixedExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 78, offset: 714},
						name: "ThrowExpr",
					},
				},
			},
		},
		{
			name: "PrefixedExpr",
			pos:  position{line: 25, col: 1, offset: 725},
			expr: &choiceExpr{
				pos: position{line: 25, col: 16, offset: 742},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 25, col: 16, offset: 742},
						exprs: []interface{}{
							&labeledExpr{
								pos:   position{line: 25, col: 16, offset: 742},
								label: "op",
								expr: &ruleRefExpr{
									pos:  position{line: 25, col: 19, offset: 745},
									name: "PrefixedOp",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 25, col: 30, offset: 756},
								name: "__",
							},
							&labeledExpr{
								pos:   position{line: 25, col: 33, offset: 759},
								label: "expr",
								expr: &ruleRefExpr{
									pos:  position{line: 25, col: 38, offset: 764},
									name: "SuffixedExpr",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 25, col: 54, offset: 780},
						name: "SuffixedExpr",
					},
				},
			},
		},
		{
			name: "PrefixedOp",
			pos:  position{line: 27, col: 1, offset: 794},
			expr: &choiceExpr{
				pos: position{line: 27, col: 16, offset: 811},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 27, col: 16, offset: 811},
						val:        "&",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 27, col: 22, offset: 817},
						val:        "!",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SuffixedExpr",
			pos:  position{line: 29, col: 1, offset: 824},
			expr: &choiceExpr{
				pos: position{line: 29, col: 16, offset: 841},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 29, col: 16, offset: 841},
						exprs: []interface{}{
							&labeledExpr{
								pos:   position{line: 29, col: 16, offset: 841},
								label: "expr",
								expr: &ruleRefExpr{
									pos:  position{line: 29, col: 21, offset: 846},
									name: "PrimaryExpr",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 29, col: 33, offset: 858},
								name: "__",
							},
							&labeledExpr{
								pos:   position{line: 29, col: 36, offset: 861},
								label: "op",
								expr: &ruleRefExpr{
									pos:  position{line: 29, col: 39, offset: 864},
									name: "SuffixedOp",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 29, col: 52, offset: 877},
						name: "PrimaryExpr",
					},
				},
			},
		},
		{
			name: "SuffixedOp",
			pos:  position{line: 31, col: 1, offset: 890},
			expr: &choiceExpr{
				pos: position{line: 31, col: 16, offset: 907},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 31, col: 16, offset: 907},
						val:        "?",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 31, col: 22, offset: 913},
						val:        "*",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 31, col: 28, offset: 919},
						val:        "+",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "PrimaryExpr",
			pos:  position{line: 33, col: 1, offset: 926},
			expr: &choiceExpr{
				pos: position{line: 33, col: 15, offset: 942},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 33, col: 15, offset: 942},
						name: "LitMatcher",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 28, offset: 955},
						name: "CharClassMatcher",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 47, offset: 974},
						name: "AnyMatcher",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 60, offset: 987},
						name: "RuleRefExpr",
					},
					&ruleRefExpr{
						pos:  position{line: 33, col: 74, offset: 1001},
						name: "SemanticPredExpr",
					},
					&seqExpr{
						pos: position{line: 33, col: 93, offset: 1020},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 33, col: 93, offset: 1020},
								val:        "(",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 33, col: 97, offset: 1024},
								name: "__",
							},
							&labeledExpr{
								pos:   position{line: 33, col: 100, offset: 1027},
								label: "expr",
								expr: &ruleRefExpr{
									pos:  position{line: 33, col: 105, offset: 1032},
									name: "Expression",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 33, col: 116, offset: 1043},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 33, col: 119, offset: 1046},
								val:        ")",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "RuleRefExpr",
			pos:  position{line: 35, col: 1, offset: 1051},
			expr: &seqExpr{
				pos: position{line: 35, col: 15, offset: 1067},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 35, col: 15, offset: 1067},
						label: "name",
						expr: &ruleRefExpr{
							pos:  position{line: 35, col: 20, offset: 1072},
							name: "IdentifierName",
						},
					},
					&notExpr{
						pos: position{line: 35, col: 35, offset: 1087},
						expr: &seqExpr{
							pos: position{line: 35, col: 38, offset: 1090},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 35, col: 38, offset: 1090},
									name: "__",
								},
								&zeroOrOneExpr{
									pos: position{line: 35, col: 41, offset: 1093},
									expr: &seqExpr{
										pos: position{line: 35, col: 43, offset: 1095},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 35, col: 43, offset: 1095},
												name: "StringLiteral",
											},
											&ruleRefExpr{
												pos:  position{line: 35, col: 57, offset: 1109},
												name: "__",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 35, col: 63, offset: 1115},
									name: "RuleDefOp",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SemanticPredExpr",
			pos:  position{line: 37, col: 1, offset: 1128},
			expr: &seqExpr{
				pos: position{line: 37, col: 20, offset: 1149},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 37, col: 20, offset: 1149},
						label: "op",
						expr: &ruleRefExpr{
							pos:  position{line: 37, col: 23, offset: 1152},
							name: "SemanticPredOp",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 37, col: 38, offset: 1167},
						name: "__",
					},
					&labeledExpr{
						pos:   position{line: 37, col: 41, offset: 1170},
						label: "code",
						expr: &ruleRefExpr{
							pos:  position{line: 37, col: 46, offset: 1175},
							name: "CodeBlock",
						},
					},
				},
			},
		},
		{
			name: "SemanticPredOp",
			pos:  position{line: 39, col: 1, offset: 1186},
			expr: &choiceExpr{
				pos: position{line: 39, col: 20, offset: 1207},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 39, col: 20, offset: 1207},
						val:        "#",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 39, col: 26, offset: 1213},
						val:        "&",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 39, col: 32, offset: 1219},
						val:        "!",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "RuleDefOp",
			pos:  position{line: 41, col: 1, offset: 1226},
			expr: &choiceExpr{
				pos: position{line: 41, col: 13, offset: 1240},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 41, col: 13, offset: 1240},
						val:        "=",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 41, col: 19, offset: 1246},
						val:        "<-",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 41, col: 26, offset: 1253},
						val:        "←",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 41, col: 37, offset: 1264},
						val:        "⟵",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SourceChar",
			pos:  position{line: 43, col: 1, offset: 1274},
			expr: &anyMatcher{
				line: 43, col: 14, offset: 1289,
			},
		},
		{
			name: "Comment",
			pos:  position{line: 44, col: 1, offset: 1291},
			expr: &choiceExpr{
				pos: position{line: 44, col: 11, offset: 1303},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 44, col: 11, offset: 1303},
						name: "MultiLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 44, col: 30, offset: 1322},
						name: "SingleLineComment",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 45, col: 1, offset: 1340},
			expr: &seqExpr{
				pos: position{line: 45, col: 20, offset: 1361},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 45, col: 20, offset: 1361},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 45, col: 25, offset: 1366},
						expr: &seqExpr{
							pos: position{line: 45, col: 27, offset: 1368},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 45, col: 27, offset: 1368},
									expr: &litMatcher{
										pos:        position{line: 45, col: 28, offset: 1369},
										val:        "*/",
										ignoreCase: false,
									},
								},
								&ruleRefExpr{
									pos:  position{line: 45, col: 33, offset: 1374},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 45, col: 47, offset: 1388},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			pos:  position{line: 46, col: 1, offset: 1393},
			expr: &seqExpr{
				pos: position{line: 46, col: 36, offset: 1430},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 46, col: 36, offset: 1430},
						val:        "/*",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 46, col: 41, offset: 1435},
						expr: &seqExpr{
							pos: position{line: 46, col: 43, offset: 1437},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 46, col: 43, offset: 1437},
									expr: &choiceExpr{
										pos: position{line: 46, col: 46, offset: 1440},
										alternatives: []interface{}{
											&litMatcher{
												pos:        position{line: 46, col: 46, offset: 1440},
												val:        "*/",
												ignoreCase: false,
											},
											&ruleRefExpr{
												pos:  position{line: 46, col: 53, offset: 1447},
												name: "EOL",
											},
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 46, col: 59, offset: 1453},
									name: "SourceChar",
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 46, col: 73, offset: 1467},
						val:        "*/",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 47, col: 1, offset: 1472},
			expr: &seqExpr{
				pos: position{line: 47, col: 21, offset: 1494},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 47, col: 21, offset: 1494},
						expr: &litMatcher{
							pos:        position{line: 47, col: 23, offset: 1496},
							val:        "//{",
							ignoreCase: false,
						},
					},
					&litMatcher{
						pos:        position{line: 47, col: 30, offset: 1503},
						val:        "//",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 47, col: 35, offset: 1508},
						expr: &seqExpr{
							pos: position{line: 47, col: 37, offset: 1510},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 47, col: 37, offset: 1510},
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 38, offset: 1511},
										name: "EOL",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 42, offset: 1515},
									name: "SourceChar",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 49, col: 1, offset: 1530},
			expr: &labeledExpr{
				pos:   position{line: 49, col: 14, offset: 1545},
				label: "ident",
				expr: &ruleRefExpr{
					pos:  position{line: 49, col: 20, offset: 1551},
					name: "IdentifierName",
				},
			},
		},
		{
			name: "IdentifierName",
			pos:  position{line: 51, col: 1, offset: 1567},
			expr: &seqExpr{
				pos: position{line: 51, col: 18, offset: 1586},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 51, col: 18, offset: 1586},
						name: "IdentifierStart",
					},
					&zeroOrMoreExpr{
						pos: position{line: 51, col: 34, offset: 1602},
						expr: &ruleRefExpr{
							pos:  position{line: 51, col: 34, offset: 1602},
							name: "IdentifierPart",
						},
					},
				},
			},
		},
		{
			name: "IdentifierStart",
			pos:  position{line: 52, col: 1, offset: 1618},
			expr: &charClassMatcher{
				pos:        position{line: 52, col: 19, offset: 1638},
				val:        "[\\pL_]",
				chars:      []rune{'_'},
				classes:    []*unicode.RangeTable{rangeTable("L")},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "IdentifierPart",
			pos:  position{line: 53, col: 1, offset: 1645},
			expr: &choiceExpr{
				pos: position{line: 53, col: 18, offset: 1664},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 53, col: 18, offset: 1664},
						name: "IdentifierStart",
					},
					&charClassMatcher{
						pos:        position{line: 53, col: 36, offset: 1682},
						val:        "[\\p{Nd}]",
						classes:    []*unicode.RangeTable{rangeTable("Nd")},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "LitMatcher",
			pos:  position{line: 55, col: 1, offset: 1692},
			expr: &seqExpr{
				pos: position{line: 55, col: 14, offset: 1707},
				exprs: []interface{}{
					&labeledExpr{
						pos:   position{line: 55, col: 14, offset: 1707},
						label: "lit",
						expr: &ruleRefExpr{
							pos:  position{line: 55, col: 18, offset: 1711},
							name: "StringLiteral",
						},
					},
					&labeledExpr{
						pos:   position{line: 55, col: 32, offset: 1725},
						label: "ignore",
						expr: &zeroOrOneExpr{
							pos: position{line: 55, col: 39, offset: 1732},
							expr: &litMatcher{
								pos:        position{line: 55, col: 39, offset: 1732},
								val:        "i",
								ignoreCase: false,
							},
						},
					},
				},
			},
		},
		{
			name: "StringLiteral",
			pos:  position{line: 57, col: 1, offset: 1738},
			expr: &choiceExpr{
				pos: position{line: 57, col: 17, offset: 1756},
				alternatives: []interface{}{
					&choiceExpr{
						pos: position{line: 57, col: 19, offset: 1758},
						alternatives: []interface{}{
							&seqExpr{
								pos: position{line: 57, col: 19, offset: 1758},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 57, col: 19, offset: 1758},
										val:        "\"",
										ignoreCase: false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 57, col: 23, offset: 1762},
										expr: &ruleRefExpr{
											pos:  position{line: 57, col: 23, offset: 1762},
											name: "DoubleStringChar",
										},
									},
									&litMatcher{
										pos:        position{line: 57, col: 41, offset: 1780},
										val:        "\"",
										ignoreCase: false,
									},
								},
							},
							&seqExpr{
								pos: position{line: 57, col: 47, offset: 1786},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 57, col: 47, offset: 1786},
										val:        "'",
										ignoreCase: false,
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 51, offset: 1790},
										name: "SingleStringChar",
									},
									&litMatcher{
										pos:        position{line: 57, col: 68, offset: 1807},
										val:        "'",
										ignoreCase: false,
									},
								},
							},
							&seqExpr{
								pos: position{line: 57, col: 74, offset: 1813},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 57, col: 74, offset: 1813},
										val:        "`",
										ignoreCase: false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 57, col: 78, offset: 1817},
										expr: &ruleRefExpr{
											pos:  position{line: 57, col: 78, offset: 1817},
											name: "RawStringChar",
										},
									},
									&litMatcher{
										pos:        position{line: 57, col: 93, offset: 1832},
										val:        "`",
										ignoreCase: false,
									},
								},
							},
						},
					},
					&choiceExpr{
						pos: position{line: 58, col: 6, offset: 1843},
						alternatives: []interface{}{
							&seqExpr{
								pos: position{line: 58, col: 8, offset: 1845},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 58, col: 8, offset: 1845},
										val:        "\"",
										ignoreCase: false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 58, col: 12, offset: 1849},
										expr: &ruleRefExpr{
											pos:  position{line: 58, col: 12, offset: 1849},
											name: "DoubleStringChar",
										},
									},
									&choiceExpr{
										pos: position{line: 58, col: 32, offset: 1869},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 58, col: 32, offset: 1869},
												name: "EOL",
											},
											&ruleRefExpr{
												pos:  position{line: 58, col: 38, offset: 1875},
												name: "EOF",
											},
										},
									},
								},
							},
							&seqExpr{
								pos: position{line: 58, col: 50, offset: 1887},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 58, col: 50, offset: 1887},
										val:        "'",
										ignoreCase: false,
									},
									&zeroOrOneExpr{
										pos: position{line: 58, col: 54, offset: 1891},
										expr: &ruleRefExpr{
											pos:  position{line: 58, col: 54, offset: 1891},
											name: "SingleStringChar",
										},
									},
									&choiceExpr{
										pos: position{line: 58, col: 74, offset: 1911},
										alternatives: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 58, col: 74, offset: 1911},
												name: "EOL",
											},
											&ruleRefExpr{
												pos:  position{line: 58, col: 80, offset: 1917},
												name: "EOF",
											},
										},
									},
								},
							},
							&seqExpr{
								pos: position{line: 58, col: 90, offset: 1927},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 58, col: 90, offset: 1927},
										val:        "`",
										ignoreCase: false,
									},
									&zeroOrMoreExpr{
										pos: position{line: 58, col: 94, offset: 1931},
										expr: &ruleRefExpr{
											pos:  position{line: 58, col: 94, offset: 1931},
											name: "RawStringChar",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 109, offset: 1946},
										name: "EOF",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			pos:  position{line: 61, col: 1, offset: 1954},
			expr: &choiceExpr{
				pos: position{line: 61, col: 20, offset: 1975},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 61, col: 20, offset: 1975},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 61, col: 20, offset: 1975},
								expr: &choiceExpr{
									pos: position{line: 61, col: 23, offset: 1978},
									alternatives: []interface{}{
										&litMatcher{
											pos:        position{line: 61, col: 23, offset: 1978},
											val:        "\"",
											ignoreCase: false,
										},
										&litMatcher{
											pos:        position{line: 61, col: 29, offset: 1984},
											val:        "\\",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 61, col: 36, offset: 1991},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 61, col: 42, offset: 1997},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 61, col: 55, offset: 2010},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 61, col: 55, offset: 2010},
								val:        "\\",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 61, col: 60, offset: 2015},
								name: "DoubleStringEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "SingleStringChar",
			pos:  position{line: 62, col: 1, offset: 2034},
			expr: &choiceExpr{
				pos: position{line: 62, col: 20, offset: 2055},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 62, col: 20, offset: 2055},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 62, col: 20, offset: 2055},
								expr: &choiceExpr{
									pos: position{line: 62, col: 23, offset: 2058},
									alternatives: []interface{}{
										&litMatcher{
											pos:        position{line: 62, col: 23, offset: 2058},
											val:        "'",
											ignoreCase: false,
										},
										&litMatcher{
											pos:        position{line: 62, col: 29, offset: 2064},
											val:        "\\",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 62, col: 36, offset: 2071},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 62, col: 42, offset: 2077},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 62, col: 55, offset: 2090},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 62, col: 55, offset: 2090},
								val:        "\\",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 62, col: 60, offset: 2095},
								name: "SingleStringEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "RawStringChar",
			pos:  position{line: 63, col: 1, offset: 2114},
			expr: &seqExpr{
				pos: position{line: 63, col: 17, offset: 2132},
				exprs: []interface{}{
					&notExpr{
						pos: position{line: 63, col: 17, offset: 2132},
						expr: &litMatcher{
							pos:        position{line: 63, col: 18, offset: 2133},
							val:        "`",
							ignoreCase: false,
						},
					},
					&ruleRefExpr{
						pos:  position{line: 63, col: 22, offset: 2137},
						name: "SourceChar",
					},
				},
			},
		},
		{
			name: "DoubleStringEscape",
			pos:  position{line: 65, col: 1, offset: 2149},
			expr: &choiceExpr{
				pos: position{line: 65, col: 22, offset: 2172},
				alternatives: []interface{}{
					&choiceExpr{
						pos: position{line: 65, col: 24, offset: 2174},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 65, col: 24, offset: 2174},
								val:        "\"",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 65, col: 30, offset: 2180},
								name: "CommonEscapeSequence",
							},
						},
					},
					&choiceExpr{
						pos: position{line: 66, col: 9, offset: 2211},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 66, col: 9, offset: 2211},
								name: "SourceChar",
							},
							&ruleRefExpr{
								pos:  position{line: 66, col: 22, offset: 2224},
								name: "EOL",
							},
							&ruleRefExpr{
								pos:  position{line: 66, col: 28, offset: 2230},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "SingleStringEscape",
			pos:  position{line: 68, col: 1, offset: 2237},
			expr: &choiceExpr{
				pos: position{line: 68, col: 22, offset: 2260},
				alternatives: []interface{}{
					&choiceExpr{
						pos: position{line: 68, col: 24, offset: 2262},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 68, col: 24, offset: 2262},
								val:        "'",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 68, col: 30, offset: 2268},
								name: "CommonEscapeSequence",
							},
						},
					},
					&choiceExpr{
						pos: position{line: 69, col: 9, offset: 2299},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 69, col: 9, offset: 2299},
								name: "SourceChar",
							},
							&ruleRefExpr{
								pos:  position{line: 69, col: 22, offset: 2312},
								name: "EOL",
							},
							&ruleRefExpr{
								pos:  position{line: 69, col: 28, offset: 2318},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "CommonEscapeSequence",
			pos:  position{line: 72, col: 1, offset: 2326},
			expr: &choiceExpr{
				pos: position{line: 72, col: 24, offset: 2351},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 72, col: 24, offset: 2351},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 43, offset: 2370},
						name: "OctalEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 57, offset: 2384},
						name: "HexEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 69, offset: 2396},
						name: "LongUnicodeEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 89, offset: 2416},
						name: "ShortUnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 73, col: 1, offset: 2435},
			expr: &choiceExpr{
				pos: position{line: 73, col: 20, offset: 2456},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 73, col: 20, offset: 2456},
						val:        "a",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 26, offset: 2462},
						val:        "b",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 32, offset: 2468},
						val:        "n",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 38, offset: 2474},
						val:        "f",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 44, offset: 2480},
						val:        "r",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 50, offset: 2486},
						val:        "t",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 56, offset: 2492},
						val:        "v",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 73, col: 62, offset: 2498},
						val:        "\\",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "OctalEscape",
			pos:  position{line: 74, col: 1, offset: 2503},
			expr: &choiceExpr{
				pos: position{line: 74, col: 15, offset: 2519},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 74, col: 15, offset: 2519},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 74, col: 15, offset: 2519},
								name: "OctalDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 74, col: 26, offset: 2530},
								name: "OctalDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 74, col: 37, offset: 2541},
								name: "OctalDigit",
							},
						},
					},
					&actionExpr{
						pos: position{line: 75, col: 7, offset: 2558},
						run: (*parser).callonOctalEscape6,
						expr: &seqExpr{
							pos: position{line: 75, col: 7, offset: 2558},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 75, col: 7, offset: 2558},
									name: "OctalDigit",
								},
								&choiceExpr{
									pos: position{line: 75, col: 20, offset: 2571},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 75, col: 20, offset: 2571},
											name: "SourceChar",
										},
										&ruleRefExpr{
											pos:  position{line: 75, col: 33, offset: 2584},
											name: "EOL",
										},
										&ruleRefExpr{
											pos:  position{line: 75, col: 39, offset: 2590},
											name: "EOF",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "HexEscape",
			pos:  position{line: 78, col: 1, offset: 2651},
			expr: &choiceExpr{
				pos: position{line: 78, col: 13, offset: 2665},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 78, col: 13, offset: 2665},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 78, col: 13, offset: 2665},
								val:        "x",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 78, col: 17, offset: 2669},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 78, col: 26, offset: 2678},
								name: "HexDigit",
							},
						},
					},
					&actionExpr{
						pos: position{line: 79, col: 7, offset: 2693},
						run: (*parser).callonHexEscape6,
						expr: &seqExpr{
							pos: position{line: 79, col: 7, offset: 2693},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 79, col: 7, offset: 2693},
									val:        "x",
									ignoreCase: false,
								},
								&choiceExpr{
									pos: position{line: 79, col: 13, offset: 2699},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 79, col: 13, offset: 2699},
											name: "SourceChar",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 26, offset: 2712},
											name: "EOL",
										},
										&ruleRefExpr{
											pos:  position{line: 79, col: 32, offset: 2718},
											name: "EOF",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LongUnicodeEscape",
			pos:  position{line: 82, col: 1, offset: 2785},
			expr: &choiceExpr{
				pos: position{line: 83, col: 5, offset: 2811},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 83, col: 5, offset: 2811},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 83, col: 5, offset: 2811},
								val:        "U",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 9, offset: 2815},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 18, offset: 2824},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 27, offset: 2833},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 36, offset: 2842},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 45, offset: 2851},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 54, offset: 2860},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 63, offset: 2869},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 83, col: 72, offset: 2878},
								name: "HexDigit",
							},
						},
					},
					&actionExpr{
						pos: position{line: 84, col: 7, offset: 2893},
						run: (*parser).callonLongUnicodeEscape12,
						expr: &seqExpr{
							pos: position{line: 84, col: 7, offset: 2893},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 84, col: 7, offset: 2893},
									val:        "U",
									ignoreCase: false,
								},
								&choiceExpr{
									pos: position{line: 84, col: 13, offset: 2899},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 84, col: 13, offset: 2899},
											name: "SourceChar",
										},
										&ruleRefExpr{
											pos:  position{line: 84, col: 26, offset: 2912},
											name: "EOL",
										},
										&ruleRefExpr{
											pos:  position{line: 84, col: 32, offset: 2918},
											name: "EOF",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ShortUnicodeEscape",
			pos:  position{line: 87, col: 1, offset: 2981},
			expr: &choiceExpr{
				pos: position{line: 88, col: 5, offset: 3008},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 88, col: 5, offset: 3008},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 88, col: 5, offset: 3008},
								val:        "u",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 88, col: 9, offset: 3012},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 88, col: 18, offset: 3021},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 88, col: 27, offset: 3030},
								name: "HexDigit",
							},
							&ruleRefExpr{
								pos:  position{line: 88, col: 36, offset: 3039},
								name: "HexDigit",
							},
						},
					},
					&actionExpr{
						pos: position{line: 89, col: 7, offset: 3054},
						run: (*parser).callonShortUnicodeEscape8,
						expr: &seqExpr{
							pos: position{line: 89, col: 7, offset: 3054},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 89, col: 7, offset: 3054},
									val:        "u",
									ignoreCase: false,
								},
								&choiceExpr{
									pos: position{line: 89, col: 13, offset: 3060},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 89, col: 13, offset: 3060},
											name: "SourceChar",
										},
										&ruleRefExpr{
											pos:  position{line: 89, col: 26, offset: 3073},
											name: "EOL",
										},
										&ruleRefExpr{
											pos:  position{line: 89, col: 32, offset: 3079},
											name: "EOF",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OctalDigit",
			pos:  position{line: 93, col: 1, offset: 3143},
			expr: &charClassMatcher{
				pos:        position{line: 93, col: 14, offset: 3158},
				val:        "[0-7]",
				ranges:     []rune{'0', '7'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 94, col: 1, offset: 3164},
			expr: &charClassMatcher{
				pos:        position{line: 94, col: 16, offset: 3181},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 95, col: 1, offset: 3187},
			expr: &charClassMatcher{
				pos:        position{line: 95, col: 12, offset: 3200},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "CharClassMatcher",
			pos:  position{line: 97, col: 1, offset: 3211},
			expr: &choiceExpr{
				pos: position{line: 97, col: 20, offset: 3232},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 97, col: 20, offset: 3232},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 97, col: 20, offset: 3232},
								val:        "[",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 97, col: 24, offset: 3236},
								expr: &choiceExpr{
									pos: position{line: 97, col: 26, offset: 3238},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 97, col: 26, offset: 3238},
											name: "ClassCharRange",
										},
										&ruleRefExpr{
											pos:  position{line: 97, col: 43, offset: 3255},
											name: "ClassChar",
										},
										&seqExpr{
											pos: position{line: 97, col: 55, offset: 3267},
											exprs: []interface{}{
												&litMatcher{
													pos:        position{line: 97, col: 55, offset: 3267},
													val:        "\\",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 97, col: 60, offset: 3272},
													name: "UnicodeClassEscape",
												},
											},
										},
									},
								},
							},
							&litMatcher{
								pos:        position{line: 97, col: 82, offset: 3294},
								val:        "]",
								ignoreCase: false,
							},
							&zeroOrOneExpr{
								pos: position{line: 97, col: 86, offset: 3298},
								expr: &litMatcher{
									pos:        position{line: 97, col: 86, offset: 3298},
									val:        "i",
									ignoreCase: false,
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 98, col: 4, offset: 3306},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 98, col: 4, offset: 3306},
								val:        "[",
								ignoreCase: false,
							},
							&zeroOrMoreExpr{
								pos: position{line: 98, col: 8, offset: 3310},
								expr: &seqExpr{
									pos: position{line: 98, col: 10, offset: 3312},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 98, col: 10, offset: 3312},
											expr: &ruleRefExpr{
												pos:  position{line: 98, col: 13, offset: 3315},
												name: "EOL",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 98, col: 19, offset: 3321},
											name: "SourceChar",
										},
									},
								},
							},
							&choiceExpr{
								pos: position{line: 98, col: 35, offset: 3337},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 98, col: 35, offset: 3337},
										name: "EOL",
									},
									&ruleRefExpr{
										pos:  position{line: 98, col: 41, offset: 3343},
										name: "EOF",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ClassCharRange",
			pos:  position{line: 101, col: 1, offset: 3351},
			expr: &seqExpr{
				pos: position{line: 101, col: 18, offset: 3370},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 101, col: 18, offset: 3370},
						name: "ClassChar",
					},
					&litMatcher{
						pos:        position{line: 101, col: 28, offset: 3380},
						val:        "-",
						ignoreCase: false,
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 32, offset: 3384},
						name: "ClassChar",
					},
				},
			},
		},
		{
			name: "ClassChar",
			pos:  position{line: 102, col: 1, offset: 3394},
			expr: &choiceExpr{
				pos: position{line: 102, col: 13, offset: 3408},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 102, col: 13, offset: 3408},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 102, col: 13, offset: 3408},
								expr: &choiceExpr{
									pos: position{line: 102, col: 16, offset: 3411},
									alternatives: []interface{}{
										&litMatcher{
											pos:        position{line: 102, col: 16, offset: 3411},
											val:        "]",
											ignoreCase: false,
										},
										&litMatcher{
											pos:        position{line: 102, col: 22, offset: 3417},
											val:        "\\",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 102, col: 29, offset: 3424},
											name: "EOL",
										},
									},
								},
							},
							&ruleRefExpr{
								pos:  position{line: 102, col: 35, offset: 3430},
								name: "SourceChar",
							},
						},
					},
					&seqExpr{
						pos: position{line: 102, col: 48, offset: 3443},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 102, col: 48, offset: 3443},
								val:        "\\",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 102, col: 53, offset: 3448},
								name: "CharClassEscape",
							},
						},
					},
				},
			},
		},
		{
			name: "CharClassEscape",
			pos:  position{line: 103, col: 1, offset: 3464},
			expr: &choiceExpr{
				pos: position{line: 103, col: 19, offset: 3484},
				alternatives: []interface{}{
					&choiceExpr{
						pos: position{line: 103, col: 21, offset: 3486},
						alternatives: []interface{}{
							&litMatcher{
								pos:        position{line: 103, col: 21, offset: 3486},
								val:        "]",
								ignoreCase: false,
							},
							&ruleRefExpr{
								pos:  position{line: 103, col: 27, offset: 3492},
								name: "CommonEscapeSequence",
							},
						},
					},
					&actionExpr{
						pos: position{line: 104, col: 7, offset: 3521},
						run: (*parser).callonCharClassEscape5,
						expr: &seqExpr{
							pos: position{line: 104, col: 7, offset: 3521},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 104, col: 7, offset: 3521},
									expr: &litMatcher{
										pos:        position{line: 104, col: 8, offset: 3522},
										val:        "p",
										ignoreCase: false,
									},
								},
								&choiceExpr{
									pos: position{line: 104, col: 14, offset: 3528},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 104, col: 14, offset: 3528},
											name: "SourceChar",
										},
										&ruleRefExpr{
											pos:  position{line: 104, col: 27, offset: 3541},
											name: "EOL",
										},
										&ruleRefExpr{
											pos:  position{line: 104, col: 33, offset: 3547},
											name: "EOF",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "UnicodeClassEscape",
			pos:  position{line: 108, col: 1, offset: 3613},
			expr: &seqExpr{
				pos: position{line: 108, col: 22, offset: 3636},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 108, col: 22, offset: 3636},
						val:        "p",
						ignoreCase: false,
					},
					&choiceExpr{
						pos: position{line: 109, col: 7, offset: 3648},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 109, col: 7, offset: 3648},
								name: "SingleCharUnicodeClass",
							},
							&actionExpr{
								pos: position{line: 110, col: 7, offset: 3677},
								run: (*parser).callonUnicodeClassEscape5,
								expr: &seqExpr{
									pos: position{line: 110, col: 7, offset: 3677},
									exprs: []interface{}{
										&notExpr{
											pos: position{line: 110, col: 7, offset: 3677},
											expr: &litMatcher{
												pos:        position{line: 110, col: 8, offset: 3678},
												val:        "{",
												ignoreCase: false,
											},
										},
										&choiceExpr{
											pos: position{line: 110, col: 14, offset: 3684},
											alternatives: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 110, col: 14, offset: 3684},
													name: "SourceChar",
												},
												&ruleRefExpr{
													pos:  position{line: 110, col: 27, offset: 3697},
													name: "EOL",
												},
												&ruleRefExpr{
													pos:  position{line: 110, col: 33, offset: 3703},
													name: "EOF",
												},
											},
										},
									},
								},
							},
							&seqExpr{
								pos: position{line: 111, col: 7, offset: 3774},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 111, col: 7, offset: 3774},
										val:        "{",
										ignoreCase: false,
									},
									&labeledExpr{
										pos:   position{line: 111, col: 11, offset: 3778},
										label: "ident",
										expr: &ruleRefExpr{
											pos:  position{line: 111, col: 17, offset: 3784},
											name: "IdentifierName",
										},
									},
									&litMatcher{
										pos:        position{line: 111, col: 32, offset: 3799},
										val:        "}",
										ignoreCase: false,
									},
								},
							},
							&actionExpr{
								pos: position{line: 112, col: 7, offset: 3809},
								run: (*parser).callonUnicodeClassEscape18,
								expr: &seqExpr{
									pos: position{line: 112, col: 7, offset: 3809},
									exprs: []interface{}{
										&litMatcher{
											pos:        position{line: 112, col: 7, offset: 3809},
											val:        "{",
											ignoreCase: false,
										},
										&ruleRefExpr{
											pos:  position{line: 112, col: 11, offset: 3813},
											name: "IdentifierName",
										},
										&choiceExpr{
											pos: position{line: 112, col: 28, offset: 3830},
											alternatives: []interface{}{
												&litMatcher{
													pos:        position{line: 112, col: 28, offset: 3830},
													val:        "]",
													ignoreCase: false,
												},
												&ruleRefExpr{
													pos:  position{line: 112, col: 34, offset: 3836},
													name: "EOL",
												},
												&ruleRefExpr{
													pos:  position{line: 112, col: 40, offset: 3842},
													name: "EOF",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SingleCharUnicodeClass",
			pos:  position{line: 116, col: 1, offset: 3925},
			expr: &charClassMatcher{
				pos:        position{line: 116, col: 26, offset: 3952},
				val:        "[LMNCPZS]",
				chars:      []rune{'L', 'M', 'N', 'C', 'P', 'Z', 'S'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "AnyMatcher",
			pos:  position{line: 118, col: 1, offset: 3963},
			expr: &litMatcher{
				pos:        position{line: 118, col: 14, offset: 3978},
				val:        ".",
				ignoreCase: false,
			},
		},
		{
			name: "ThrowExpr",
			pos:  position{line: 120, col: 1, offset: 3983},
			expr: &choiceExpr{
				pos: position{line: 120, col: 13, offset: 3997},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 120, col: 13, offset: 3997},
						exprs: []interface{}{
							&litMatcher{
								pos:        position{line: 120, col: 13, offset: 3997},
								val:        "%",
								ignoreCase: false,
							},
							&litMatcher{
								pos:        position{line: 120, col: 17, offset: 4001},
								val:        "{",
								ignoreCase: false,
							},
							&labeledExpr{
								pos:   position{line: 120, col: 21, offset: 4005},
								label: "label",
								expr: &ruleRefExpr{
									pos:  position{line: 120, col: 27, offset: 4011},
									name: "IdentifierName",
								},
							},
							&litMatcher{
								pos:        position{line: 120, col: 42, offset: 4026},
								val:        "}",
								ignoreCase: false,
							},
						},
					},
					&actionExpr{
						pos: position{line: 121, col: 4, offset: 4033},
						run: (*parser).callonThrowExpr8,
						expr: &seqExpr{
							pos: position{line: 121, col: 4, offset: 4033},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 121, col: 4, offset: 4033},
									val:        "%",
									ignoreCase: false,
								},
								&litMatcher{
									pos:        position{line: 121, col: 8, offset: 4037},
									val:        "{",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 12, offset: 4041},
									name: "IdentifierName",
								},
								&ruleRefExpr{
									pos:  position{line: 121, col: 27, offset: 4056},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "CodeBlock",
			pos:  position{line: 125, col: 1, offset: 4127},
			expr: &choiceExpr{
				pos: position{line: 125, col: 13, offset: 4141},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 125, col: 13, offset: 4141},
						run: (*parser).callonCodeBlock2,
						expr: &seqExpr{
							pos: position{line: 125, col: 13, offset: 4141},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 125, col: 13, offset: 4141},
									val:        "{",
									ignoreCase: false,
								},
								&labeledExpr{
									pos:   position{line: 125, col: 17, offset: 4145},
									label: "code",
									expr: &ruleRefExpr{
										pos:  position{line: 125, col: 22, offset: 4150},
										name: "Code",
									},
								},
								&litMatcher{
									pos:        position{line: 125, col: 27, offset: 4155},
									val:        "}",
									ignoreCase: false,
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 131, col: 4, offset: 4265},
						run: (*parser).callonCodeBlock8,
						expr: &seqExpr{
							pos: position{line: 131, col: 4, offset: 4265},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 131, col: 4, offset: 4265},
									val:        "{",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 131, col: 8, offset: 4269},
									name: "Code",
								},
								&ruleRefExpr{
									pos:  position{line: 131, col: 13, offset: 4274},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Code",
			pos:  position{line: 135, col: 1, offset: 4339},
			expr: &zeroOrMoreExpr{
				pos: position{line: 135, col: 8, offset: 4348},
				expr: &choiceExpr{
					pos: position{line: 135, col: 10, offset: 4350},
					alternatives: []interface{}{
						&oneOrMoreExpr{
							pos: position{line: 135, col: 10, offset: 4350},
							expr: &seqExpr{
								pos: position{line: 135, col: 12, offset: 4352},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 135, col: 12, offset: 4352},
										expr: &charClassMatcher{
											pos:        position{line: 135, col: 13, offset: 4353},
											val:        "[{}]",
											chars:      []rune{'{', '}'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&ruleRefExpr{
										pos:  position{line: 135, col: 18, offset: 4358},
										name: "SourceChar",
									},
								},
							},
						},
						&seqExpr{
							pos: position{line: 135, col: 34, offset: 4374},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 135, col: 34, offset: 4374},
									val:        "{",
									ignoreCase: false,
								},
								&ruleRefExpr{
									pos:  position{line: 135, col: 38, offset: 4378},
									name: "Code",
								},
								&litMatcher{
									pos:        position{line: 135, col: 43, offset: 4383},
									val:        "}",
									ignoreCase: false,
								},
							},
						},
					},
				},
			},
		},
		{
			name: "__",
			pos:  position{line: 137, col: 1, offset: 4391},
			expr: &zeroOrMoreExpr{
				pos: position{line: 137, col: 6, offset: 4398},
				expr: &choiceExpr{
					pos: position{line: 137, col: 8, offset: 4400},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 137, col: 8, offset: 4400},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 137, col: 21, offset: 4413},
							name: "EOL",
						},
						&ruleRefExpr{
							pos:  position{line: 137, col: 27, offset: 4419},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "_",
			pos:  position{line: 138, col: 1, offset: 4430},
			expr: &zeroOrMoreExpr{
				pos: position{line: 138, col: 5, offset: 4436},
				expr: &choiceExpr{
					pos: position{line: 138, col: 7, offset: 4438},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 138, col: 7, offset: 4438},
							name: "Whitespace",
						},
						&ruleRefExpr{
							pos:  position{line: 138, col: 20, offset: 4451},
							name: "MultiLineCommentNoLineTerminator",
						},
					},
				},
			},
		},
		{
			name: "Whitespace",
			pos:  position{line: 140, col: 1, offset: 4488},
			expr: &charClassMatcher{
				pos:        position{line: 140, col: 14, offset: 4503},
				val:        "[ \\t\\r]",
				chars:      []rune{' ', '\t', '\r'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EOL",
			pos:  position{line: 141, col: 1, offset: 4511},
			expr: &litMatcher{
				pos:        position{line: 141, col: 7, offset: 4519},
				val:        "\n",
				ignoreCase: false,
			},
		},
		{
			name: "EOS",
			pos:  position{line: 142, col: 1, offset: 4524},
			expr: &choiceExpr{
				pos: position{line: 142, col: 7, offset: 4532},
				alternatives: []interface{}{
					&seqExpr{
						pos: position{line: 142, col: 7, offset: 4532},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 142, col: 7, offset: 4532},
								name: "__",
							},
							&litMatcher{
								pos:        position{line: 142, col: 10, offset: 4535},
								val:        ";",
								ignoreCase: false,
							},
						},
					},
					&seqExpr{
						pos: position{line: 142, col: 16, offset: 4541},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 142, col: 16, offset: 4541},
								name: "_",
							},
							&zeroOrOneExpr{
								pos: position{line: 142, col: 18, offset: 4543},
								expr: &ruleRefExpr{
									pos:  position{line: 142, col: 18, offset: 4543},
									name: "SingleLineComment",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 142, col: 37, offset: 4562},
								name: "EOL",
							},
						},
					},
					&seqExpr{
						pos: position{line: 142, col: 43, offset: 4568},
						exprs: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 142, col: 43, offset: 4568},
								name: "__",
							},
							&ruleRefExpr{
								pos:  position{line: 142, col: 46, offset: 4571},
								name: "EOF",
							},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 144, col: 1, offset: 4576},
			expr: &notExpr{
				pos: position{line: 144, col: 7, offset: 4584},
				expr: &anyMatcher{
					line: 144, col: 8, offset: 4585,
				},
			},
		},
	},
}

func (c *current) onGrammar1(initializer, rules interface{}) (interface{}, error) {
	return unwrap(initializer) + unwrap(rules), nil
}

func (p *parser) callonGrammar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrammar1(stack["initializer"], stack["rules"])
}

func (c *current) onOctalEscape6() (interface{}, error) {
	return nil, errors.New("invalid octal escape")
}

func (p *parser) callonOctalEscape6() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOctalEscape6()
}

func (c *current) onHexEscape6() (interface{}, error) {
	return nil, errors.New("invalid hexadecimal escape")
}

func (p *parser) callonHexEscape6() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHexEscape6()
}

func (c *current) onLongUnicodeEscape12() (interface{}, error) {
	return nil, errors.New("invalid Unicode escape")
}

func (p *parser) callonLongUnicodeEscape12() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLongUnicodeEscape12()
}

func (c *current) onShortUnicodeEscape8() (interface{}, error) {
	return nil, errors.New("invalid Unicode escape")
}

func (p *parser) callonShortUnicodeEscape8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onShortUnicodeEscape8()
}

func (c *current) onCharClassEscape5() (interface{}, error) {
	return nil, errors.New("invalid escape character")
}

func (p *parser) callonCharClassEscape5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCharClassEscape5()
}

func (c *current) onUnicodeClassEscape5() (interface{}, error) {
	return nil, errors.New("invalid Unicode class escape")
}

func (p *parser) callonUnicodeClassEscape5() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnicodeClassEscape5()
}

func (c *current) onUnicodeClassEscape18() (interface{}, error) {
	return nil, errors.New("Unicode class not terminated")

}

func (p *parser) callonUnicodeClassEscape18() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUnicodeClassEscape18()
}

func (c *current) onThrowExpr8() (interface{}, error) {
	return nil, errors.New("throw expression not terminated")
}

func (p *parser) callonThrowExpr8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onThrowExpr8()
}

func (c *current) onCodeBlock2(code interface{}) (interface{}, error) {
	if bytes.Count(c.text, []byte("\n")) <= 1 {
		return c.text, nil
	}
	return formatSection(c.text)
}

func (p *parser) callonCodeBlock2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCodeBlock2(stack["code"])
}

func (c *current) onCodeBlock8() (interface{}, error) {
	return nil, errors.New("code block not terminated")
}

func (p *parser) callonCodeBlock8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCodeBlock8()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := make(storeDict, len(p.cur.state))
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return fmt.Sprintf("%s %s %s", strings.Join(list[:len(list)-1], sep), lastSep, list[len(list)-1])
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := fmt.Sprintf("%q%s", lit.val, ignoreCase)
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
